### ISSUE TITLE
Falta foto y descripción

### ISSUE THREAD

**Issue by asanzo** [pdepjm/2021-kata0-prensentacion-nullspace1#1]
¡Hola, @nullspace1 !
Contanos un poco sobre vos y subí tu foto. ¿pudiste? ¿te damos una mano con algo?

**Comment by nullspace1** [comment]
Estuve un poco complicado al principio con la instalacion pero creo que ya tengo todo. Lo unico no baje del todo en el documento de la tarea y me comi el F y G, oops.

**Comment by asanzo** [comment]
Jajajaj aguanten las milas de pollo.
